# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAd():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ad(self):
    self.driver.get("https://www.google.com/")
    self.driver.set_window_size(778, 759)
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.NAME, "q").send_keys("calc")
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > td:nth-child(2) > .A2W7l > .XRsWPe").click()
    assert self.driver.find_element(By.ID, "cwos").text == "2"
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) .mF5fo > .MEdqYd").click()
    assert self.driver.find_element(By.ID, "cwos").text == "2 +"
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(4) > td:nth-child(2) > .A2W7l > .XRsWPe").click()
    assert self.driver.find_element(By.ID, "cwos").text == "2 + 2"
    self.driver.find_element(By.CSS_SELECTOR, ".UUhRt").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".vUGUtc").text == "2 + 2 ="
    assert self.driver.find_element(By.ID, "cwos").text == "4"
  
